title: Yijun Wang
logo: /assets/photo3.png
description: I am Yijun Wang from Nanjing University, now a Postdoctor in the School of Astronomy and Space Science. Between 2010 and 2014, I studied plant science at Huazhong Agriculture University. Between 2014 and 2021, I studied astronomy at University of Science and Technology of China. Between 2019 and 2020, I was a visiting PhD student at SRON and Leiden University. My works include X-ray spectral variabilities in blazars, warm absorber outflows, ambient circumnuclear medium around supermassive black hole, and radio activities of AGN. 
show_downloads: False
#google_analytics:
theme: jekyll-theme-minimal
#remote_theme: pages-themes/minimal@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one
#gem "github-pages", group: :jekyll_plugins
