title: Yijun Wang
logo: /assets/photo3.png
description: My works include X-ray spectral variabilities in blazars, warm absorber outflows, ambient circumnuclear medium around supermassive black hole, and radio activities of AGN.
show_downloads: False
#google_analytics:
theme: jekyll-theme-minimal
#remote_theme: pages-themes/minimal@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one
#gem "github-pages", group: :jekyll_plugins
