title: Welcome to Yijun Wang's homepage!
description: Yijun Wang is a postdoc in Nanjing University now.
show_downloads: False
google_analytics:
theme: cayman
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
gem "github-pages", group: :jekyll_plugins
